try{ //AÇÃO A EXECUTAR
    a
} catch(e) { // O QUE FAZER SE FOR UM ERRO
    console.log(`algo deu errado '${e}'`)
} finally{
    console.log("sim")
}